INSERT INTO registration_project (vo,label) VALUES ('/nz/bestgrid','BeSTGRID');
INSERT INTO registration_project (vo,label) VALUES ('/nz/bluefern','BlueFern');
INSERT INTO registration_project (vo,label) VALUES ('/nz/demo','Demonstration');
INSERT INTO registration_project (vo,label) VALUES ('/nz/grid-dev','New Zealand Grid Development');
INSERT INTO registration_project (vo,label) VALUES ('/nz/landcare','Landcare Research');
INSERT INTO registration_project (vo,label) VALUES ('/nz/landcare/admin','Landcare Research Administrators');
INSERT INTO registration_project (vo,label) VALUES ('/nz/landcare/osgeo','Landcare Research OSGeo');
INSERT INTO registration_project (vo,label) VALUES ('/nz/nesi','New Zealand eScience Infrastructure');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa','The University of Auckland');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/civil-engineering','Department of Civil Engineering, The University of Auckland');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/mechanical-engineering','Department of Mechanical Engineering, The University of Auckland');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-chem','Department of Chemistry, The University of Auckland');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-chem/gaussian','Department of Chemistry Gaussian Software Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-chem/vasp','Department of Chemistry VASP Software Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-evol','The University of Auckland Computational Evolution Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-sci','Department of Computer Science, The University of Auckland');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-sci/research','Department of Computer Science Research Programmers');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/engineering-science','Department of Engineering Science, The University of Auckland');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/epigen','Developmental Epigenetics, The Liggins Institute');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/math','Department of Mathematics, The University of Auckland');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/mnl','The Movement Neuroscience Laboratory, The University of Auckland');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/qualitas','The Qualitas Corpus Research Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/quantum-optics','The Quantum Optics Research Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/stats','The Department of Statistics, The University of Auckland');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/stats/staff','The Department of Statistics Academic Staff');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/stats/students','The Department of Statistics Research Students');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/stats/wtccc','The Wellcome Trust Case Control Consortium');
INSERT INTO registration_project (vo,label) VALUES ('/nz/virtual-screening','The Virtual Screening for Drug Discovery Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/virtual-screening','The Virtual Screening for Drug Discovery Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/virtual-screening/jobs','The Auckland Cancer Society Research Centre Jobs');
INSERT INTO registration_project (vo,label) VALUES ('/nz/virtual-screening/sbs-structural-biology','The School of Biological Sciences Structural Biology Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/virtual-screening/acsrc','The Auckland Cancer Society Research Centre');
