DELETE FROM registration_project;
ALTER TABLE registration_project AUTO_INCREMENT = 0;
INSERT INTO registration_project (vo,label) VALUES ('/nz/bestgrid','NeSI transitional services (formerly BeSTGRID)');
INSERT INTO registration_project (vo,label) VALUES ('/nz/bluefern','BlueFern');
INSERT INTO registration_project (vo,label) VALUES ('/nz/demo','Demonstration');
INSERT INTO registration_project (vo,label) VALUES ('/nz/grid-dev','New Zealand Grid Development');
INSERT INTO registration_project (vo,label) VALUES ('/nz/landcare','Landcare Research');
INSERT INTO registration_project (vo,label) VALUES ('/nz/landcare/admin','Landcare Research Administrators');
INSERT INTO registration_project (vo,label) VALUES ('/nz/landcare/osgeo','Landcare Research OSGeo');
INSERT INTO registration_project (vo,label) VALUES ('/nz/nesi','New Zealand eScience Infrastructure');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/abi','Auckland Bioengineering Institute');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa','The University of Auckland');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/foe','The University of Auckland Faculty of Engineering');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/civil-engineering','Department of Civil Engineering');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/mechanical-engineering','Department of Mechanical Engineering');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-chem','Department of Chemistry');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-chem/gaussian','Department of Chemistry Gaussian Software Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-chem/vasp','Department of Chemistry VASP 4.6 Software Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-chem/vasp5.2','Department of Chemistry VASP 5.2 Software Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-evol','Computational Evolution Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-sci','Department of Computer Science');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-sci/research','Department of Computer Science Research Programmers');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/engineering-science','Department of Engineering Science');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/engineering-science/geothermal','Department of Engineering Science Geothermal Research Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/epigen','Developmental Epigenetics, The Liggins Institute');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/fos','The University of Auckland Faculty of Science');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/math','Department of Mathematics');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/mnl','Movement Neuroscience Laboratory');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/qualitas','Qualitas Corpus Research Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/quantum-optics','Quantum Optics Research Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/stats','Department of Statistics');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/stats/staff','Department of Statistics Academic Staff');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/stats/students','Department of Statistics Research Students');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/stats/wtccc','Department of Statistics Wellcome Trust Case Control Consortium (WTCCC) Research Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/virtual-screening','Virtual Screening for Drug Discovery Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/virtual-screening/jobs','Virtual Screening Gold Software Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/virtual-screening/sbs-structural-biology','Virtual Screening Structural Biology Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/virtual-screening/acsrc','Auckland Cancer Society Research Centre');
