DELETE FROM registration_project;
ALTER TABLE registration_project AUTO_INCREMENT = 0;
INSERT INTO registration_project (vo,label) VALUES ('/nz/bestgrid','NeSI transitional services (formerly BeSTGRID)');
INSERT INTO registration_project (vo,label) VALUES ('/nz/bluefern','BlueFern');
INSERT INTO registration_project (vo,label) VALUES ('/nz/demo','Demonstration');
INSERT INTO registration_project (vo,label) VALUES ('/nz/grid-dev','New Zealand Grid Development');
INSERT INTO registration_project (vo,label) VALUES ('/nz/landcare','Landcare Research');
INSERT INTO registration_project (vo,label) VALUES ('/nz/landcare/admin','Landcare Research Administrators');
INSERT INTO registration_project (vo,label) VALUES ('/nz/landcare/osgeo','Landcare Research OSGeo');
INSERT INTO registration_project (vo,label) VALUES ('/nz/nesi','New Zealand eScience Infrastructure');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/abi','Auckland Bioengineering Institute');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa','The University of Auckland');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/foe','The University of Auckland Faculty of Engineering');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/civil-engineering','UoA Department of Civil Engineering');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/mechanical-engineering','UoA Department of Mechanical Engineering');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-chem','UoA Department of Chemistry');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-chem/gaussian','UoA Department of Chemistry Gaussian Software Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-chem/vasp','UoA Department of Chemistry VASP 4.6 Software Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-chem/vasp5.2','UoA Department of Chemistry VASP 5.2 Software Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-evol','UoA Computational Evolution Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-sci','UoA Department of Computer Science');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/comp-sci/research','UoA Department of Computer Science Research Programmers');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/engineering-science','UoA Department of Engineering Science');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/engineering-science/geothermal','UoA Department of Engineering Science Geothermal Research Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/epigen','Developmental Epigenetics, The Liggins Institute');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/fos','The University of Auckland Faculty of Science');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/math','UoA Department of Mathematics');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/mnl','UoA Movement Neuroscience Laboratory');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/qualitas','UoA Qualitas Corpus Research Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/quantum-optics','UoA Quantum Optics Research Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/stats','UoA Department of Statistics');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/stats/staff','UoA Department of Statistics Academic Staff');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/stats/students','UoA Department of Statistics Research Students');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/stats/wtccc','UoA Department of Statistics Wellcome Trust Case Control Consortium (WTCCC) Research Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/virtual-screening','Virtual Screening for Drug Discovery Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/virtual-screening/jobs','Virtual Screening Gold Software Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/virtual-screening/sbs-structural-biology','Virtual Screening Structural Biology Group');
INSERT INTO registration_project (vo,label) VALUES ('/nz/virtual-screening/acsrc','Auckland Cancer Society Research Centre');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoo','The University of Otago');
INSERT INTO registration_project (vo,label) VALUES ('/nz/agresearch','AgResearch ');
INSERT INTO registration_project (vo,label) VALUES ('/nz/aut','AUT University');
INSERT INTO registration_project (vo,label) VALUES ('/nz/esr','ESR');
INSERT INTO registration_project (vo,label) VALUES ('/nz/gns','GNS Science');
INSERT INTO registration_project (vo,label) VALUES ('/nz/irl','Industrial Research Limited');
INSERT INTO registration_project (vo,label) VALUES ('/nz/massey','Massey University');
INSERT INTO registration_project (vo,label) VALUES ('/nz/niwa','NIWA');
INSERT INTO registration_project (vo,label) VALUES ('/nz/pfr','Plant and Food Research');
INSERT INTO registration_project (vo,label) VALUES ('/nz/vuw','Victoria University of Wellington');
INSERT INTO registration_project (vo,label) VALUES ('/nz/waikato','The University of Waikato');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/physics','UoA Department of Physics');
INSERT INTO registration_project (vo,label) VALUES ('/nz/uoa/physics/cosmology','UoA Department of Physics Cosmology Research Group');
